# Generated by Django 6.0.5 on 2026-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='applied', max_length=50)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(max_length=300)),
            ],
        ),
    ]
